dataset:
  name: tiny_imagenet_c
  resize: 64
  severities:
  - 3
  - 4
  - 5
model:
  name: mobilenet_v2_gn
run_id: tin_c_mnv2_zorro_full
seed: 42
training:
  batch_size: 32
  epochs: 1
  eps: 0.005
  lambda: 4
  method: zorro
