dataset:
  max_samples: 5000
  name: tinyimagenet_c
  split: test
model:
  name: resnet20_gn
run_id: tinyimagenet_resnet20_gn_rotta
seed: 7
training:
  adapt_lr: 5e-4
  batch_size: 32
  delta: 0.1
  epochs: 1
  method: rotta
